### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by renanbr** [renanbr/bibtex-parser#32]
General:

- ~~Require PHP ^7.1 (https://github.com/renanbr/bibtex-parser/commit/2b69a51a9492eb77ed134297bb10ad299a42f191, https://github.com/renanbr/bibtex-parser/commit/0bc19cfbee7a329809bdcb5355308ad6bbece295, https://github.com/renanbr/bibtex-parser/commit/f95f7e6df0d0140332dec20a346e1545aa71469d)~~ moved to #41
    - More readable code, less comments to explain intentions
    - [7.1 will be the oldest version with active support in one month](http://php.net/supported-versions.php)
- [x] Exceptions refactoring ~~Replace `ParseException` with `Exception`~~ (https://github.com/renanbr/bibtex-parser/commit/48c7048550e6eda8ad3311a278e4efc5f9502f0a, https://github.com/renanbr/bibtex-parser/commit/facdf1f4a8b7fb4cbf4ff28d9f13797fc38bbaf6)
    - ~~To be used for general purpose, not only for "parser" stuff~~
    - Create a namespace `Exception`, and put all needed exceptions inside it
    - Make exceptions implement a base `ExceptionInterface`
- [x] Make `Listener` able to manage "entry processors" instead of "tag processors" (https://github.com/renanbr/bibtex-parser/commit/aed4c2ef7f0acb00f3b0a6626462dc0b9b6e461f)
    - It'll make possible to inject tags, or to process multiple at the same time
- [x] No longer use variable reference in processors (https://github.com/renanbr/bibtex-parser/commit/aed4c2ef7f0acb00f3b0a6626462dc0b9b6e461f)
    - Processor must return the modified entry
    - The code will be more readable
    - There is no real need to use references in this case
- [x] Translate v1 tag processors into entry processors (https://github.com/renanbr/bibtex-parser/commit/5f3efda6092917508ab206b90fad86169ecd66fa, https://github.com/renanbr/bibtex-parser/commit/22e8f1c66d591fe85da25b771ce3f38ac7ddc9a0)
    - To keep current features working as well
- [x] Move "citation key" and "tag name case" processing from Listener to specialized entry processors (https://github.com/renanbr/bibtex-parser/commit/e05182d8d730625d5686934ef44317b2d6b329cf, https://github.com/renanbr/bibtex-parser/commit/40a970985dbc555f6fd72d5c2ff7d1b3d7313ba1)
    - Listener becomes simpler
    - Listener becomes more extensible

Coming entry processors:

- `DateProcessor` #28
    - Appends `_date` tag with a `DateTime` instance
- `DoiToUrlProcessor` #37 
    - Fills `url` tag if this one is missing using `DOI`
- `TrimProcessor` #36 
    - Strips whitespace from the beginning and end of all tags' values

Internals:

- [x] Normalize "tag" term (https://github.com/renanbr/bibtex-parser/commit/ef89c9cdc8a34ab2204429694f72c84789fc889e and https://github.com/renanbr/bibtex-parser/commit/703408daf747136c10ac280ba432695779cf7f3e)
    - ~~It will be always be referenced as "tag" (not as "tag" or "key")~~
    - Introduce "tag name" and "tag content" terms
- [x] Review dev files setup (https://github.com/renanbr/bibtex-parser/commit/2b69a51a9492eb77ed134297bb10ad299a42f191, https://github.com/renanbr/bibtex-parser/commit/b74f28d38d41ef7ec1231cb78a4e140b197c0101, https://github.com/renanbr/bibtex-parser/commit/7eeb8482676bfcd0c306b23a2b6a6b4802ceb3df, https://github.com/renanbr/bibtex-parser/commit/0bc19cfbee7a329809bdcb5355308ad6bbece295, https://github.com/renanbr/bibtex-parser/commit/ec0bd3853d9c17a61864ad78a0dff8d3ddd98ba9, https://github.com/renanbr/bibtex-parser/commit/b4afc78b4b161d49acc965493156457dd2d9622d, https://github.com/renanbr/bibtex-parser/commit/2bbe936bd021b1313605f9754b488e1e16762894, https://github.com/renanbr/bibtex-parser/commit/11871a7741dd9a1f96935d07b03bd9efe3a0981d, https://github.com/renanbr/bibtex-parser/commit/d00519809935e01efb2288233bdbc73087e77fa5, https://github.com/renanbr/bibtex-parser/commit/bfb0089071d0e6a500b595f4114fbc2a717670a9, https://github.com/renanbr/bibtex-parser/commit/f02af76071d5f46c107aeae20ed1160f7434984f)
    - .editorconfig, .php_cs, .travis.yml, composer.json, phpunit.xml ...

Thoughts:

- ~~Handle entries as objects instead of arrays~~

**Comment by renanbr** [comment]
Done!

https://github.com/renanbr/bibtex-parser/releases/tag/2.0.0
